# report_generator.py
import os
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deep Learning Algorithm Analysis Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background-color: #f4f4f4; color: #333; }}
        .container {{ background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }}
        h2 {{ color: #4CAF50; margin-top: 30px; }}
        .experiment-params {{ background-color: #e9e9e9; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
        .experiment-params p {{ margin: 5px 0; }}
        .grid-container {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; }}
        .model-card {{ border: 1px solid #ddd; border-radius: 5px; padding: 15px; background-color: #f9f9f9; }}
        .model-card h3 {{ margin-top: 0; color: #555; }}
        .metrics-table {{ width: 100%; border-collapse: collapse; margin-bottom: 15px; }}
        .metrics-table th, .metrics-table td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        .metrics-table th {{ background-color: #e9e9e9; }}
        .plot-image {{ max-width: 100%; height: auto; border: 1px solid #ccc; margin-top: 10px; }}
        footer {{ text-align: center; margin-top: 30px; font-size: 0.9em; color: #777; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Functional Analysis Report</h1>
        <div class="experiment-params">
            <h2>Experiment Parameters</h2>
            <p><strong>Report Generated:</strong> {report_time}</p>
            <p><strong>Dataset Size (Train Fraction):</strong> {train_data_fraction_param}</p>
            <p><strong>MLP Epochs:</strong> {epochs_param}</p>
            <p><strong>MLP Activation:</strong> {activation_param}</p>
        </div>

        <div class="grid-container">
            {model_cards_html}
        </div>
        
        <footer>
            Generated by Functional Analysis Script
        </footer>
    </div>
</body>
</html>
"""

MODEL_CARD_TEMPLATE = """
<div class="model-card">
    <h3>{model_name}</h3>
    <p><strong>Task Type:</strong> {task_type}</p>
    <h4>Metrics:</h4>
    <table class="metrics-table">
        <tr><th>Metric</th><th>Value</th></tr>
        {metrics_rows_html}
    </table>
    <h4>Plots:</h4>
    {plots_html}
</div>
"""

def generate_html_report(all_model_results, train_data_fraction, epochs, activation, output_dir="reports"):
    """
    Generates an HTML report from the collected model results.

    Args:
        all_model_results (list): A list of dictionaries, where each dict is the result from a model.
        train_data_fraction (float): The fraction of training data used.
        epochs (int): Number of epochs used for MLP.
        activation (str): Activation function used for MLP.
        output_dir (str): Directory to save the report.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"analysis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    filepath = os.path.join(output_dir, filename)

    model_cards_html = ""
    for model_result in all_model_results:
        if not model_result:  # Skip if a model failed or returned None
            continue

        metrics_rows_html = ""
        for metric, value in model_result.get("metrics", {}).items():
            metrics_rows_html += f"<tr><td>{metric}</td><td>{value}</td></tr>\n"

        plots_html = ""
        for plot_name, base64_img in model_result.get("plots", {}).items():
            if base64_img:
                plot_title = plot_name.replace("_", " ").title()
                plots_html += f"<div><p><strong>{plot_title}:</strong></p><img src='data:image/png;base64,{base64_img}' alt='{plot_title}' class='plot-image'></div>\n"
            else:
                plots_html += f"<div><p><strong>{plot_name.replace('_', ' ').title()}:</strong> Plot not available.</p></div>\n"


        model_cards_html += MODEL_CARD_TEMPLATE.format(
            model_name=model_result.get("model_name", "Unknown Model"),
            task_type=model_result.get("task_type", "N/A"),
            metrics_rows_html=metrics_rows_html,
            plots_html=plots_html
        )

    full_html = HTML_TEMPLATE.format(
        report_time=report_time,
        train_data_fraction_param=f"{train_data_fraction*100:.0f}% of {50000} samples", # Referring to TRAIN_BASE_SIZE
        epochs_param=epochs,
        activation_param=activation,
        model_cards_html=model_cards_html
    )

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_html)
        print(f"\nHTML report generated: {os.path.abspath(filepath)}")
    except IOError as e:
        print(f"Error writing HTML report: {e}")

if __name__ == '__main__':
    print("Report generator module loaded.")
    # Example usage (for testing this module standalone - won't produce real plots without model results)
    # dummy_results = [
    #     {
    #         "model_name": "Dummy Model 1 (classification)",
    #         "task_type": "classification",
    #         "metrics": {"Accuracy": "0.95", "Loss": "0.123"},
    #         "plots": {"confusion_matrix": "base64_string_placeholder_cm", "loss_curve": None}
    #     },
    #     {
    #         "model_name": "Dummy Model 2 (regression)",
    #         "task_type": "regression",
    #         "metrics": {"RMSE": "10.5", "R2": "0.88"},
    #         "plots": {"true_vs_predicted": "base64_string_placeholder_reg"}
    #     }
    # ]
    # generate_html_report(dummy_results, train_data_fraction=0.8, epochs=50, activation="relu")